---
name: CI

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container: elixir:1.18-alpine
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add --update bash openssl git build-base cmake tar # tar is required for cache action
          mix local.hex --force && mix local.rebar --force

      - name: Cache build and dependencies
        uses: actions/cache@v4
        id: cache-lock-file
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install elixir dependencies and build project
        if: steps.cache-lock-file.outputs.cache-hit != 'true'
        env:
          MIX_ENV: test
        run: |
          mix deps.get
          mix compile --warning-as-errors

      - name: Run linters and tests
        env:
          MIX_ENV: test
        run: mix ci
